<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="<?php echo $this->locale; ?>">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="keywords" content="<?php print $this->translate('比特币, bitcoin, 比特币交易平台, 兑换') ?>" />
	<?php if(!$this->btcxo): ?>
		<meta name="description" content="<?php print $this->translate('比特币中国是中国首家 Bitcoin 比特币与人民币的交易平台。您可以在这里使用人民币购买比特币，也可以使用比特币兑换人民币。安全、便捷！') ?>" />
	<?php endif; ?>

	<?php echo $this->headTitle() ?>

	<link rel="icon" href="<?php echo $this->cdnurl('img/favicon.ico?v=2'); ?>" type="image/x-icon" />
	<link rel="shortcut icon" href="<?php echo $this->cdnurl('img/favicon.ico?v=2'); ?>" type="image/x-icon" />
	<style type="text/css">
    body{background: #fff;font-size:20px;text-align:center}
    body.mac{font-family:Arial,"微软雅黑";}
    .content{width:50%;margin: 0 auto;padding:20px;line-height:35px;background: #fafafa;border: 1px solid #d5d5d5}
    .compatibility {width:80%;margin: 0 auto}
    .compatibility ul {width: 60%;margin: 0 auto}
    img {max-width: 100%;}
	</style>
</head>
<body>
  <img src="<?php print $this->cdnurl('new/assets_front/img/logo.png?v=3')?>" alt="BTCChina" />
  <div class="content">
    为了给您提供更好的交易体验，请使用我们支持的浏览器：IE10-11、谷歌、火狐、Safari或者搜狗浏览器。<br>
    <a href="https://www.mozilla.org/en-US/firefox/all/" target="_blank">点击下载火狐浏览器</a>
    <a href="https://www.google.com/chrome/" target="_blank">点击下载谷歌浏览器</a><br />
    To improve your user experience, please use the following supported browsers: IE10-11, Chrome, Firefox, Safari, and Sogou.<br>
    <a href="https://www.mozilla.org/en-US/firefox/all/" target="_blank">Click here to download Firefox</a>
    <a href="https://www.google.com/chrome/" target="_blank">Click here to download Google Chrome</a>
  </div>
  <div class="compatibility">
    <div id="ie11" style="display:none">
      <h5>如果你使用的是Internet Explorer 11，可能您已经启用兼容性视图设置，请按照以下步骤禁用兼容性视图：</h5>
      1.请您打开您的IE并且打开点击左上角设置按钮，选择兼容性视图设置<br />
      <img src="<?php print $this->cdnurl('assets/images/block/IE11-1-zh.png')?>" alt="BTCChina" /><br/>
      2.请把"btcchina.com"从列表中删除，并且把"在兼容性视图中显示Intranet站点前的勾去掉"<br />
      <img src="<?php print $this->cdnurl('assets/images/block/IE11-2-zh.png')?>" alt="BTCChina" /><br/>
      <h5>Please Disable Internet Explorer 11 Compatibility mode</h5>
      <ul>
        <li>In IE11, access the menu by pressing the ALT key to bring up the top menu and the go to Tools > Developer Tools, or press F12 on your keyboard</li>
        <li>In the bottom window of your web browser a new section will appear starting with F12 display</li>
        <li>Scroll down to locate the Emulation mode (icon with desktop screen and mobile screen)</li>
        <li>Set document mode to Edge (Default)</li>
        <li>Set User agent string to Default</li>
        <i>Note: you may wish to set the document mode and user agent string to IE10 as not all Claro features have been fully tested with IE11﻿.</i>
      </ul>
    </div>
    <div id="ie10" style="display:none">
      <h5>如果你使用的是Internet Explorer 10，可能您已经启用兼容性视图设置，请按照以下步骤禁用兼容性视图：</h5>
      1.请您打开您的IE并且打开点击左上角设置按钮，选择兼容性视图设置<br />
      <img src="<?php print $this->cdnurl('assets/images/block/IE10-1-zh.png')?>" alt="BTCChina" /><br/>
      2.请把"btcchina.com"从列表中删除，并且把"在兼容性视图中显示Intranet站点前的勾去掉"<br />
      <img src="<?php print $this->cdnurl('assets/images/block/IE10-2-zh.png')?>" alt="BTCChina" /><br/>
      <h5>Please Disable Internet Explorer 10 Compatibility mode<</h5>
      <ul>
        <li>In IE10, access the menu by pressing the ALT key to bring up the top menu and the go to Tools > Developer Tools, or press F12 on your keyboard</li>
        <li>In the bottom window of your web browser a new row will appear starting with "File"</li>
        <li>Click on Browser Mode and change it to IE10 (NOT the IE 10 Compatibility View)</li>
        <li>Click on Document Mode and change it to IE10 standards</li>
        <li>Once changed, access Claro again and attempt to log in. You may close the developer Tools bar</li>
      </ul>
    </div>
  </div>
  <script type="text/javascript">
    var ua = navigator.userAgent.toLowerCase();
    if (ua.indexOf("trident/6.0") > -1) {
      document.getElementById('ie10').style.display = "block";
    } else if (ua.indexOf("trident/7.0") > -1) {
      document.getElementById('ie11').style.display = "block";
    }
    if(ua.indexOf('mac os x') != -1) {
      document.body.className = "mac";
    }
  </script>
</body>
</html>
